// src/components/TiltCard.vue
<script setup lang="ts">
import { ref, computed } from 'vue';

const props = defineProps<{
    className?: string;
}>();

const cardRef = ref<HTMLElement | null>(null);
const x = ref(0);
const y = ref(0);

const rotateX = computed(() => -y.value * 14);
const rotateY = computed(() => x.value * 14);

const sheenX = computed(() => (x.value + 0.5) * 100);
const sheenY = computed(() => (y.value + 0.5) * 100);
const sheenOpacity = computed(() => {
    const base = 0.15;
    return base - Math.abs(x.value) * 0.15;
});

const handleMouseMove = (e: MouseEvent) => {
    if (!cardRef.value) return;
    const rect = cardRef.value.getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;
    const mouseX = e.clientX - rect.left;
    const mouseY = e.clientY - rect.top;
    const xPct = mouseX / width - 0.5;
    const yPct = mouseY / height - 0.5;
    x.value = xPct;
    y.value = yPct;
};

const handleMouseLeave = () => {
    x.value = 0;
    y.value = 0;
};
</script>

<template>
    <div
        ref="cardRef"
        class="relative overflow-hidden cursor-pointer"
        :class="props.className"
        @mousemove="handleMouseMove"
        @mouseleave="handleMouseLeave"
        :style="{
            transform: `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) scale(1.02)`,
            transition: 'transform 0.1s ease-out',
            transformStyle: 'preserve-3d',
            zIndex: 10
        }"
    >
        <slot />

        <!-- Sheen Overlay -->
        <div
            class="pointer-events-none absolute inset-0 z-20 mix-blend-overlay"
            :style="{
                background: `radial-gradient(circle at center, rgba(255,255,255,0.8) 0%, transparent 50%)`,
                opacity: sheenOpacity,
                left: `${sheenX}%`,
                top: `${sheenY}%`,
                transform: 'translate(-50%, -50%)',
                width: '200%',
                height: '200%'
            }"
        />
    </div>
</template>

// app/components/motion/TiltCard.tsx
'use client';

import React, { useRef } from 'react';
import { motion, useMotionValue, useSpring, useTransform } from 'framer-motion';

interface TiltCardProps {
    children: React.ReactNode;
    className?: string;
    onClick?: () => void;
    style?: React.CSSProperties;
}

export default function TiltCard({ children, className = '', onClick, style }: TiltCardProps) {
    const ref = useRef<HTMLDivElement>(null);
    const x = useMotionValue(0);
    const y = useMotionValue(0);

    const mouseXSpring = useSpring(x, { stiffness: 300, damping: 30 });
    const mouseYSpring = useSpring(y, { stiffness: 300, damping: 30 });

    // Subtle tilt
    const rotateX = useTransform(mouseYSpring, [-0.5, 0.5], ["7deg", "-7deg"]);
    const rotateY = useTransform(mouseXSpring, [-0.5, 0.5], ["-7deg", "7deg"]);

    // Sheen follows mouse
    const sheenX = useTransform(mouseXSpring, [-0.5, 0.5], ["100%", "0%"]);
    const sheenY = useTransform(mouseYSpring, [-0.5, 0.5], ["100%", "0%"]);
    const sheenOpacity = useTransform(mouseXSpring, [-0.5, 0, 0.5], [0.15, 0, 0.15]);

    const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
        if (!ref.current) return;
        const rect = ref.current.getBoundingClientRect();

        const width = rect.width;
        const height = rect.height;

        const mouseX = e.clientX - rect.left;
        const mouseY = e.clientY - rect.top;

        const xPct = mouseX / width - 0.5;
        const yPct = mouseY / height - 0.5;

        x.set(xPct);
        y.set(yPct);
    };

    const handleMouseLeave = () => {
        x.set(0);
        y.set(0);
    };

    return (
        <motion.div
            ref={ref}
            className={`relative overflow-hidden ${className}`}
            onMouseMove={handleMouseMove}
            onMouseLeave={handleMouseLeave}
            onClick={onClick}
            style={{
                rotateX,
                rotateY,
                transformStyle: "preserve-3d",
                ...style
            }}
            whileHover={{ scale: 1.02, zIndex: 10 }}
            whileTap={{ scale: 0.98 }}
            transition={{ type: "spring", stiffness: 400, damping: 30 }}
        >
            {children}

            {/* Sheen Overlay */}
            <motion.div
                className="pointer-events-none absolute inset-0 z-20 mix-blend-overlay"
                style={{
                    background: `radial-gradient(circle at center, rgba(255,255,255,0.8) 0%, transparent 50%)`,
                    opacity: sheenOpacity,
                    left: sheenX,
                    top: sheenY,
                    transform: 'translate(-50%, -50%)',
                    width: '200%',
                    height: '200%'
                }}
            />
        </motion.div>
    );
}
